const $=s=>document.querySelector(s);let lines=[], playing=false, startAt=0, startPerf=0, raf=0, active=-1, lock=null;
const settings={fontSize:64,leadTime:0,lineHeight:1.35,autoScroll:true,wakeLock:true};
const demo=`[00:05.00]这里是第一句歌词
[00:09.20]下一句将在九秒二开始
[00:14.00]现场演出时，直接点任意歌词即可跳转
[00:20.50]字号和提前量都可以自由调整
[00:27.00]祝你每一场演出都稳稳当当`;
function parseLrc(text){const out=[];const stamp=/\[(\d{1,2}(?::\d{1,2}){1,2})(?:[.:](\d{1,3}))?\]/g;text.replace(/^\uFEFF/,'').replace(/\r/g,'').split('\n').forEach(row=>{let lyric=row.replace(/\[[^\]]+\]/g,'').trim();const stamps=[...row.matchAll(stamp)];stamps.forEach(m=>{const parts=m[1].split(':').map(Number);const seconds=parts.length===3?parts[0]*3600+parts[1]*60+parts[2]:parts[0]*60+parts[1];const fraction=m[2]?Number('0.'+m[2]):0;out.push({time:seconds+fraction,text:lyric||'♪'});});});return out.sort((a,b)=>a.time-b.time)}
function fmt(s){s=Math.max(0,s);return `${String(Math.floor(s/60)).padStart(2,'0')}:${(s%60).toFixed(1).padStart(4,'0')}`}
function save(){localStorage.setItem('stagecue-lines',JSON.stringify(lines));localStorage.setItem('stagecue-settings',JSON.stringify(settings));}
function load(){try{lines=JSON.parse(localStorage.getItem('stagecue-lines'))||[];Object.assign(settings,JSON.parse(localStorage.getItem('stagecue-settings'))||{})}catch{}}
function toast(t){const x=$('#toast');x.textContent=t;x.classList.add('show');clearTimeout(x.timer);x.timer=setTimeout(()=>x.classList.remove('show'),1700)}
function renderEdit(){const box=$('#lyricsEditor');box.innerHTML='';lines.forEach((l,i)=>{const row=document.createElement('div');row.className='edit-line';row.innerHTML=`<input aria-label="时间" value="${fmt(l.time)}"><input aria-label="歌词" value="${escapeHtml(l.text)}"><button title="删除">×</button>`;const [time,text,del]=row.children;time.onchange=()=>{let v=time.value.trim().split(':');let n=Number(v[0])*60+Number(v[1]||0);if(Number.isFinite(n)){l.time=n;lines.sort((a,b)=>a.time-b.time);renderEdit();renderStage();save()}};text.oninput=()=>{l.text=text.value;renderStage();save()};del.onclick=()=>{lines.splice(i,1);renderEdit();renderStage();save()};box.append(row)})}
function escapeHtml(t){return t.replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function renderStage(){const box=$('#cueList');box.innerHTML='';box.style.setProperty('--cue-size',settings.fontSize+'px');box.style.setProperty('--cue-line-height',settings.lineHeight);lines.forEach((l,i)=>{const el=document.createElement('div');el.className='cue-line';el.dataset.index=i;el.innerHTML=`<span class="cue-time">${fmt(l.time)}</span>${escapeHtml(l.text)}`;el.onclick=()=>jump(i);box.append(el)});applySettings()}
function applySettings(){['fontSize','leadTime','lineHeight'].forEach(k=>{$('#'+k).value=settings[k]});$('#fontSizeValue').textContent=settings.fontSize+' px';$('#leadTimeValue').textContent=settings.leadTime.toFixed(1)+' 秒';$('#lineHeightValue').textContent=settings.lineHeight;$('#autoScroll').checked=settings.autoScroll;$('#wakeLock').checked=settings.wakeLock;$('#cueList').style.setProperty('--cue-size',settings.fontSize+'px');$('#cueList').style.setProperty('--cue-line-height',settings.lineHeight);save()}
function now(){return playing?startAt+(performance.now()-startPerf)/1000:startAt}
function tick(){const t=now();$('#currentTime').textContent=fmt(t);const cueTime=t+settings.leadTime;let ix=-1;for(let i=0;i<lines.length;i++)if(lines[i].time<=cueTime)ix=i;setActive(ix);if(playing)raf=requestAnimationFrame(tick)}
function setActive(ix){if(ix===active)return;active=ix;document.querySelectorAll('.cue-line').forEach((el,i)=>{el.classList.toggle('current',i===ix);el.classList.toggle('past',i<ix)});const next=lines[ix+1];$('#nextCue').textContent=next?`下一句 ${fmt(next.time)}`:'— 结束 —';if(ix>=0&&settings.autoScroll){const el=document.querySelector(`.cue-line[data-index="${ix}"]`);el?.scrollIntoView({behavior:'smooth',block:'center'})}}
function play(){if(!lines.length)return toast('请先导入或编辑歌词');playing=!playing;if(playing){startPerf=performance.now();$('#playBtn').textContent='❚❚ 暂停';requestLock();raf=requestAnimationFrame(tick)}else{$('#playBtn').textContent='▶ 继续';cancelAnimationFrame(raf);releaseLock()} }
function jump(i){if(i<0||i>=lines.length)return;startAt=Math.max(0,lines[i].time-settings.leadTime);startPerf=performance.now();active=-1;tick();toast(`已跳转：${fmt(lines[i].time)}`)}
async function requestLock(){if(settings.wakeLock&&'wakeLock'in navigator)try{lock=await navigator.wakeLock.request('screen')}catch{}}async function releaseLock(){try{await lock?.release()}catch{}lock=null}
function setMode(show){$('#editor').classList.toggle('hidden',show);$('#stage').classList.toggle('hidden',!show);$('#editModeBtn').classList.toggle('active',!show);$('#showModeBtn').classList.toggle('active',show);document.body.classList.toggle('showing',show);if(show){renderStage();active=-1;tick()}else{playing=false;cancelAnimationFrame(raf);releaseLock()}}
$('#lrcFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader;r.onload=()=>{lines=parseLrc(r.result);renderEdit();renderStage();save();toast(`已导入 ${lines.length} 句歌词`)};r.readAsText(f)};
$('#parsePasteBtn').onclick=()=>{const p=parseLrc($('#pasteArea').value);if(!p.length)return toast('未识别到时间戳，请检查格式');lines=p;renderEdit();renderStage();save();toast(`已解析 ${lines.length} 句歌词`)};
$('#loadDemoBtn').onclick=()=>{$('#pasteArea').value=demo;$('#parsePasteBtn').click()};$('#clearBtn').onclick=()=>{if(confirm('确定清空所有歌词吗？')){lines=[];renderEdit();renderStage();save()}};$('#addLineBtn').onclick=()=>{lines.push({time:(lines.at(-1)?.time||0)+5,text:'新的一句歌词'});renderEdit();renderStage();save()};
$('#editModeBtn').onclick=()=>setMode(false);$('#showModeBtn').onclick=()=>setMode(true);$('#exitStageBtn').onclick=()=>setMode(false);$('#playBtn').onclick=play;$('#prevBtn').onclick=()=>jump(Math.max(0,active-1));$('#nextBtn').onclick=()=>jump(Math.min(lines.length-1,active+1));$('#resetBtn').onclick=()=>{startAt=0;startPerf=performance.now();active=-1;tick();toast('已回到开头')};
$('#openSettingsBtn').onclick=()=>$('#settings').classList.toggle('hidden');$('#closeSettingsBtn').onclick=()=>$('#settings').classList.add('hidden');$('#fullscreenBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
function stepFontSize(delta){settings.fontSize=Math.max(28,Math.min(160,settings.fontSize+delta));applySettings();tick();toast(`字号 ${settings.fontSize} px`)}
$('#fontDownBtn').onclick=()=>stepFontSize(-4);$('#fontUpBtn').onclick=()=>stepFontSize(4);
['fontSize','leadTime','lineHeight'].forEach(k=>$('#'+k).oninput=e=>{settings[k]=Number(e.target.value);applySettings();tick()});$('#autoScroll').onchange=e=>{settings.autoScroll=e.target.checked;save()};$('#wakeLock').onchange=e=>{settings.wakeLock=e.target.checked;save()};
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&playing)requestLock()});document.addEventListener('keydown',e=>{if($('#stage').classList.contains('hidden'))return;if(e.code==='Space'){e.preventDefault();play()}if(e.code==='ArrowDown')jump(Math.min(lines.length-1,active+1));if(e.code==='ArrowUp')jump(Math.max(0,active-1))});
load();renderEdit();renderStage();applySettings();
